version: '3.8'

services:
  # web:
  #   build: .
  #   ports:
  #     - 3000:3000
  #   volumes:
  #     - .:/usr/src/app
  #   # command: >
  #   #   sh -c "go run ./cmd/api/ --db-dsn=postgres://ffwriter:password@localhost/FF-Writer?sslmode=disable
  #   env_file:
  #     - ./fanfiction-backend/.envrc
  #   links:
  #     - db
  #   depends_on:
  #     - db
  #   networks:
  #     - ffwriter-network

  db:
    image: postgres:alpine
    env_file:
      - ./fanfiction-backend/.envrc
    environment:
      - POSTGRES_USER=ffwriter
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=FF-Writer
    ports:
      - "5432"
    volumes:
      - postgres-db:/var/lib/postgresql/data
    networks:
      - ffwriter-network  
    healthcheck:
      test: pg_isready -U ffwriter -d FF-Writer
      interval: 10s
      timeout: 3s
      retries: 5

  migrate:
    image: migrate/migrate
    depends_on:
      - db      
    volumes:
      - ./fanfiction-backend/migrations:/migrations 
    # entrypoint: "migrate -database postgres://ffwriter:password@db:5432/FF-Writer?sslmode=disable -path /migrations"
    # command: up
    command: ["-path", "/migrations", "-database", "postgres://ffwriter:password@db:5432/FF-Writer?sslmode=disable", "up"]
    links:
      - db
    networks:
      - ffwriter-network

volumes:
  postgres-db:


networks:
  ffwriter-network:
